import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

async function render() {
  const workerUrl = new URL("../dist/server/index.js", import.meta.url);
  workerUrl.searchParams.set("test", `${process.pid}-${Date.now()}`);
  const { default: worker } = await import(workerUrl.href);
  return worker.fetch(new Request("http://localhost/", { headers: { accept: "text/html" } }), { ASSETS: { fetch: async () => new Response("Not found", { status: 404 }) } }, { waitUntil() {}, passThroughOnException() {} });
}

test("renders the APK Cleaner Studio preview", async () => {
  const response = await render();
  assert.equal(response.status, 200);
  assert.match(response.headers.get("content-type") ?? "", /^text\/html\b/i);
  const html = await response.text();
  const packageInfo = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
  assert.ok(html.includes(`APK Cleaner Studio ${packageInfo.version}`));
  assert.match(html, /Yerel Android paket işleme stüdyosu/i);
});

test("ships the current local studio interface", async () => {
  const [html, script, boot, style, theme, packageText, repoIcon, websiteIcon, telegramIcon, githubIcon] = await Promise.all([
    readFile(new URL("../studio/web/index.html", import.meta.url), "utf8"),
    readFile(new URL("../studio/web/app.js", import.meta.url), "utf8"),
    readFile(new URL("../studio/web/boot.js", import.meta.url), "utf8"),
    readFile(new URL("../studio/web/styles.css", import.meta.url), "utf8"),
    readFile(new URL("../studio/web/theme.css", import.meta.url), "utf8"),
    readFile(new URL("../package.json", import.meta.url), "utf8"),
    readFile(new URL("../studio/web/apk-repo-icon.png", import.meta.url)),
    readFile(new URL("../studio/web/icons/website.svg", import.meta.url), "utf8"),
    readFile(new URL("../studio/web/icons/telegram-plane.svg", import.meta.url), "utf8"),
    readFile(new URL("../studio/web/icons/github.svg", import.meta.url), "utf8"),
  ]);
  const packageVersion = JSON.parse(packageText).version;
  assert.match(html, /styles\.css/i);
  assert.match(html, /theme\.css/i);
  assert.match(html, /boot\.css/i);
  assert.match(html, /boot\.js/i);
  assert.doesNotMatch(html, /<script(?![^>]*\bsrc=)[^>]*>/i);
  assert.doesNotMatch(html, /<style\b/i);
  assert.doesNotMatch(html, /studio\.css|class="app-rail"|LIVE PIPELINE/i);
  assert.match(html, new RegExp(`v${packageVersion.replaceAll(".", "\\.")}`, "i"));
  assert.match(html, /Sec-CH-UA-Model[\s\S]*Sec-CH-UA-Form-Factors/i);
  assert.match(html, /\.apk,\.apks,\.apkm,\.xapk/i);
  assert.match(html, /Hedef cihaz yapılandırmasını seç/i);
  assert.match(html, /Dönüştürme sırasında reklam yaması uygula/i);
  assert.match(html, /Yamalanan APK’yı optimize et/i);
  assert.match(html, /RES kaynak korumasını kaldır/i);
  assert.match(html, /0dp \+ gone/i);
  assert.match(html, /© 2026 APK Repo Grubu/i);
  assert.match(html, /id="specialThanksTitle"[\s\S]*Özel Teşekkürler/i);
  assert.match(html, /id="supporterList"/i);
  assert.match(html, /<b>Zeki Kurt<\/b><small>Daimi Destekçi<\/small>/i);
  assert.match(html, /<b>SHADOW<\/b><small>Destekçi<\/small>/i);
  assert.doesNotMatch(html, /𝕲𝖆𝖟𝖎/i);
  assert.match(html, /id="reportViewerDownload"[\s\S]*Raporu indir/i);
  assert.match(html, /YEREL AĞ OTURUMLARI/i);
  assert.doesNotMatch(html, /id="secureNotice"|HTTPS ile aç/i);
  assert.match(html, /id="startGuide"[\s\S]*Paket içeride kalır/i);
  assert.match(html, /class="process-route"[\s\S]*Raporlu çıktı/i);
  assert.match(html, /id="startGuide"[\s\S]*class="features starter-content"[\s\S]*<\/div>\s*<aside\b/i);
  assert.match(html, /id="mobileHttpsBanner"[\s\S]*CA sertifikasını indir/i);
  assert.match(boot, /https:\/\/\$\{location\.host\}\/api\/status\?tls_probe=1/i);
  assert.match(boot, /location\.replace\(`https:\/\/\$\{location\.host\}/i);
  assert.doesNotMatch(html, /id="workspaceArchitecture"|Yerel işlem zinciri/i);
  assert.match(html, /href="\/local-ca\.crt"[\s\S]*CA sertifikasını indir/i);
  assert.match(html, /Kaynak dosyaya dokunmadan analiz, düzenleme ve çıktı üretimini/i);
  assert.match(html, /http-equiv="Accept-CH"/i);
  assert.match(html, /ESKİ İŞLEMLER/i);
  assert.match(html, /id="toolList"[\s\S]*data-tool="java"[\s\S]*data-tool="zipalign"/i);
  assert.match(html, /class="setup setup-pending"/i);
  assert.match(html, /id="clientList"[\s\S]*class="client-row client-skeleton"/i);
  assert.match(html, /id="historyList"[\s\S]*class="history-row history-skeleton"/i);
  assert.doesNotMatch(html, /Tüm hakları saklıdır/i);
  assert.match(script, /requestAnimationFrame\(animateProgress\)/i);
  assert.match(script, /reportViewerDownload[\s\S]*\/api\/jobs\/\$\{encodeURIComponent\(jobId\)\}\/report/i);
  assert.match(script, /const showStartGuide = id === "#selectView" \|\| id === "#workingView" \|\| id === "#resultView"/i);
  assert.match(script, /\$\("\.workspace-primary > \.features"\)[\s\S]*?#analysisView/i);
  assert.match(script, /pollInFlight:\s*false,\s*jobRunning:\s*false/i);
  assert.match(script, /waitForJobResult/i);
  assert.doesNotMatch(script, /setInterval\(pollJob/i);
  assert.doesNotMatch(script, /secure_public_url|secureNotice|HTTPS ile aç/i);
  assert.match(script, /cache:\s*"no-store"/i);
  assert.doesNotMatch(script, /\$\("#toolList"\)\.innerHTML\s*=/i);
  assert.match(script, /setupButton\.classList\.toggle\("setup-hidden"/i);
  assert.match(script, /list\.setAttribute\("aria-busy", "false"\)/i);
  assert.match(script, /renderClients\(data\.clients \|\| \[\]\)/i);
  assert.match(script, /registerClientDetails\(\)/i);
  assert.match(script, /getHighEntropyValues\(\["model", "platform", "platformVersion", "formFactors"\]\)/i);
  assert.match(script, /resolvePublicIpv4\(\)/i);
  assert.match(script, /navigator\.brave\?\.isBrave/i);
  assert.match(script, /return "Microsoft Edge"/i);
  assert.match(script, /return "Samsung Internet"/i);
  assert.match(script, /https:\/\/api\.ipify\.org\?format=json/i);
  assert.doesNotMatch(script, /format=jsonp|createElement\("script"\)/i);
  assert.doesNotMatch(script, /api64\.ipify\.org/i);
  assert.doesNotMatch(html, /Keenetic’in gerçek-IP|IPify üzerinden/i);
  assert.doesNotMatch(script, /requestDeviceNameOnce|DEVICE_NAME_PROMPT_KEY|Tarayıcı cihaz modelini paylaşmadı/i);
  assert.match(script, /\/api\/client\/manage/i);
  assert.match(script, /apk_cleaner_client_id/i);
  assert.match(script, /function renderAccessBlocked\(\)/i);
  assert.match(script, /document\.body\.className = "access-blocked-page"/i);
  assert.match(script, /response\.status === 403/i);
  assert.match(script, /data-manage-client/i);
  assert.match(script, /access-request-badge/i);
  assert.match(script, /Yöneticiden erişim iste/i);
  assert.match(script, /İzin ver/i);
  assert.match(script, /Reddet/i);
  assert.match(script, /Engelle/i);
  assert.match(script, /Listeden sil/i);
  assert.match(script, /const patterns = \[/i);
  assert.match(script, /Android\\s\[\^;\)\]\*;\\s\*\(\[\^;\)\]\+\?\)\\s\+Build/i);
  assert.match(script, /X-Client-ID/i);
  assert.match(script, /uiScheduler\.add\("status", refreshStatus, 10000\)/i);
  assert.match(script, /\/api\/history/i);
  assert.match(script, /data-history-reuse/i);
  assert.match(script, /data-history-delete/i);
  assert.match(script, /\/api\/jobs\/\$\{jobId\}\/delete/i);
  assert.match(script, /normalize_resources:\s*false/);
  assert.match(script, /strip_debug/);
  assert.match(script, /optimize_apk/);
  assert.match(script, /deobfuscate_resources/);
  assert.match(script, /normalize_dex/);
  assert.match(html, /id="normalizeDex"/i);
  assert.match(html, />Gelişmiş</i);
  assert.doesNotMatch(html, />Kapsamlı</i);
  assert.match(style, /\.topbar/i);
  assert.match(style, /\.hero/i);
  assert.match(theme, /\.split-choice/i);
  assert.match(theme, /\.split-selector::before\s*\{\s*content:\s*none/i);
  assert.match(theme, /\.split-choices \.split-choice\s*\{[\s\S]*?min-height:\s*54px[\s\S]*?padding:\s*9px 10px/i);
  assert.match(theme, /\.option\s*\{[\s\S]*?grid-template-columns:\s*26px minmax\(0, 1fr\) auto[\s\S]*?min-height:\s*54px/i);
  assert.match(theme, /\.option::after\s*\{[\s\S]*?content:\s*"SEÇİLİ"/i);
  assert.match(theme, /\.option b\s*\{\s*font-size:\s*12px;\s*line-height:\s*1\.25/i);
  assert.match(theme, /\.option p\s*\{[\s\S]*?font-size:\s*10px;[\s\S]*?line-height:\s*1\.5/i);
  assert.match(theme, /@media \(max-width:\s*620px\)[\s\S]*?\.view\s*\{\s*padding:\s*14px;/i);
  assert.match(theme, /html, body\s*\{\s*overflow-x:\s*clip/i);
  assert.match(theme, /@media \(max-width:\s*620px\)[\s\S]*?\.topbar\s*\{[\s\S]*?position:\s*sticky;[\s\S]*?top:\s*0;[\s\S]*?z-index:\s*100/i);
  assert.match(theme, /\.option\s*\{[\s\S]*?min-height:\s*64px;[\s\S]*?padding:\s*11px 12px/i);
  assert.match(theme, /\.footer-links\s*\{\s*grid-template-columns:\s*repeat\(3, minmax\(0, 1fr\)\);\s*gap:\s*8px/i);
  assert.match(theme, /\.footer-links a\s*\{\s*min-height:\s*64px;/i);
  assert.match(html, /<small>GITHUB<\/small><b>Projeyi incele<\/b>/i);
  assert.match(theme, /@media \(min-width:\s*901px\)[\s\S]*?\.operation p\s*\{\s*font-size:\s*11\.5px;\s*line-height:\s*1\.55/i);
  assert.match(theme, /@media \(min-width:\s*901px\)[\s\S]*?\.option p\s*\{\s*font-size:\s*10\.5px;\s*line-height:\s*1\.55/i);
  assert.match(theme, /@media \(min-width:\s*901px\)[\s\S]*?\.footer-bottom\s*\{\s*font-size:\s*11px;\s*line-height:\s*1\.45/i);
  assert.match(theme, /\.features,\s*\.site-footer\s*\{\s*content-visibility:\s*auto/i);
  assert.match(theme, /\.client-list\s*\{[\s\S]*?max-height:\s*390px[\s\S]*?scrollbar-gutter:\s*stable/i);
  assert.match(theme, /\.client-row\s*\{[\s\S]*?grid-template-columns:\s*8px minmax\(0, 1fr\) auto/i);
  assert.match(theme, /\.client-row > div b\s*\{[\s\S]*?white-space:\s*normal[\s\S]*?-webkit-line-clamp:\s*2/i);
  assert.match(theme, /\.client-actions/i);
  assert.match(theme, /\.client-row\.is-blocked/i);
  assert.match(theme, /\.access-request-badge/i);
  assert.match(theme, /\.access-blocked/i);
  assert.match(theme, /\.access-blocked-page[\s\S]*?min-height:\s*100dvh/i);
  assert.match(theme, /@media \(max-width:\s*520px\)[\s\S]*?\.access-blocked/i);
  assert.match(theme, /\.history-row nav \.history-delete:hover/i);
  assert.match(theme, /html\s*\{\s*-webkit-tap-highlight-color:\s*transparent/i);
  assert.match(theme, /:active:not\(:disabled\):not\(\[aria-disabled="true"\]\):not\(:has\(input:disabled\)\)\s*\{\s*transform:\s*scale\(\.992\)/i);
  assert.match(theme, /--card:\s*rgba\(255,255,255,\.48\)/i);
  assert.match(theme, /html\[data-theme="dark"\][\s\S]*?--card:\s*rgba\(13,22,19,\.46\)/i);
  assert.match(theme, /--bg:\s*var\(--paper\)/i);
  assert.match(theme, /@keyframes installed-app-actions-in\s*\{[\s\S]*?clip-path:\s*inset\(0 0 100% 0 round 10px\)[\s\S]*?translate3d\(0,0,0\)/i);
  assert.match(theme, /\.installed-app-actions\s*\{[^}]*animation:\s*installed-app-actions-in\s+\.26s\s+cubic-bezier\(\.22,\.61,\.36,1\)/i);
  assert.match(theme, /\.app-dialog-actions \.destructive\s*\{[^}]*background:\s*#c84e42;\s*\}/i);
  assert.match(theme, /\.app-dialog-actions \.primary,[\s\S]*?\.report-viewer-actions \.secondary:hover\s*\{\s*box-shadow:\s*none/i);
  assert.match(theme, /\.special-thanks\s*\{[^}]*background:\s*var\(--card\)/i);
  assert.match(theme, /scrollbar-gutter:\s*stable/i);
  assert.match(theme, /\.supporter-list\s*\{[^}]*repeat\(4,\s*minmax\(0,\s*1fr\)\)/i);
  assert.match(html, /ʙʏᴛᴇᴄʜɴᴏ/);
  assert.doesNotMatch(html, /id="messageOriginalInput"|id="messageCompareButton"/);
  assert.match(html, /id="messageScanButton"/);
  assert.match(html, /id="messageRiskAcknowledged"/);
  assert.match(html, /id="toast"[^>]*role="status"[^>]*aria-live="polite"/);
  assert.match(html, /id="messageRiskError"[^>]*role="alert"/);
  assert.match(script, /state\.messageTargets\.includes\(item\.id\)/);
  assert.match(script, /input\.setAttribute\("aria-invalid", "true"\)[\s\S]*?messageRiskError[\s\S]*?scrollIntoView[\s\S]*?return;/);
  assert.doesNotMatch(script, /input\.closest\("label"\)\.scrollIntoView[\s\S]{0,160}?toast\(message\)/);
  const installedRenderer = script.slice(script.indexOf("function renderInstalledApps("), script.indexOf("function processInstalledApp("));
  assert.match(installedRenderer, /new Map\(\[\.\.\.list\.querySelectorAll\('\[data-installed-entry\]'\)\]/);
  assert.match(installedRenderer, /if \(icon\.getAttribute\('src'\) !== item\.icon\) icon\.setAttribute\('src', item\.icon\)/);
  assert.doesNotMatch(installedRenderer, /list\.innerHTML\s*=/);
  assert.doesNotMatch(theme, /installed-app-icon-in|\.installed-app-icon\s*\{[^}]*opacity:\s*0/i);
  assert.match(theme, /\.toast\s*\{[^}]*z-index:\s*90/i);
  assert.match(theme, /\.message-review-body > \.message-risk-error\s*\{[^}]*color:\s*var\(--orange\)/i);
  assert.match(script, /messageScanTask && messageScanTask\.key !== key/);
  assert.match(theme, /\.network-badge svg\s*\{[^}]*width:\s*20px;\s*height:\s*20px/);
  assert.doesNotMatch(theme, /\.app-dialog-card\s*\{[^}]*backdrop-filter/i);
  assert.doesNotMatch(theme, /\.report-viewer-card\s*\{[^}]*backdrop-filter/i);
  assert.match(theme, /html\[data-theme="light"\] \.app-dialog,[\s\S]*?background:\s*rgba\(224,232,228,\.28\)/i);
  assert.match(theme, /html\[data-theme="light"\] \.installed-app-row\s*\{[\s\S]*?background:\s*rgba\(255,255,255,\.58\)/i);
  assert.match(theme, /#downloadButton\s*\{[^}]*justify-content:\s*center[^}]*text-align:\s*center/i);
  assert.match(theme, /#downloadButton > span\s*\{[^}]*position:\s*absolute[^}]*right:\s*20px/i);
  assert.match(theme, /#cleanButton,\s*#downloadButton\s*\{[^}]*justify-content:\s*center[^}]*padding:\s*10px 44px/i);
  assert.match(theme, /#cleanButton > span,\s*#downloadButton > span\s*\{[^}]*position:\s*absolute/i);
  assert.match(script, /function captureInstalledAppPositions\(list\)[\s\S]*?getBoundingClientRect\(\)/i);
  assert.match(script, /function animateInstalledAppReflow\(list, positions\)[\s\S]*?translate3d[\s\S]*?duration:\s*360/i);
  assert.doesNotMatch(theme.match(/@keyframes installed-app-actions-in\s*\{[\s\S]*?\n\}/i)?.[0] || "", /max-height:/i);
  assert.match(theme, /\.installed-apps-list\s*\{[^}]*contain:\s*layout paint style/i);
  assert.match(theme, /\.installed-app-entry\.selected \.installed-app-row\s*\{[^}]*border-radius:\s*14px/i);
  assert.doesNotMatch(theme, /\.installed-app-entry\.selected \.installed-app-row\s*\{[^}]*border-bottom-(?:left|right)-radius/i);
  assert.match(script, /<b title="\$\{escapeHTML\(client\.display_name/i);
  assert.match(theme, /@media \(min-width:\s*901px\)[\s\S]*?\.workspace\s*\{\s*grid-template-columns:\s*minmax\(0, 1fr\) 340px/i);
  assert.match(script, /workspace\.dataset\.stage\s*=\s*id\.slice\(1\)\.replace/i);
  assert.doesNotMatch(theme, /\.workspace\[data-stage="working"\][\s\S]{0,200}?grid-template-columns/i);
  assert.match(script, /patchAdsSelected[\s\S]*?setOperation\(operation, toggle = false\)/i);
  assert.match(script, /const hasConvertChoice = Boolean\(state\.analysis\?\.split_merged\)/i);
  assert.match(script, /canClearStandalonePatch = toggle && !hasConvertChoice/i);
  assert.match(script, /function installedPackageFilename\(item\)[\s\S]*?item\?\.version[\s\S]*?\.apks/i);
  assert.match(script, /const profilesEnabled = hasAds && \(enabled === null \? true : Boolean\(enabled\)\)/i);
  assert.match(script, /button\.disabled = !profilesEnabled/i);
  assert.match(script, /updateAdProfileAvailability\(wantsAds\)/i);
  assert.doesNotMatch(script, /!state\.patchAdsSelected\) state\.patchAdsSelected = true/i);
  assert.match(html, /data-operation="patch" aria-pressed="true"/i);
  assert.match(theme, /\.start-onboarding\s*\{[\s\S]*?min-height:\s*520px[\s\S]*?grid-template-columns:/i);
  assert.match(theme, /\.workspace-primary > \.features\s*\{[\s\S]*?width:\s*100%[\s\S]*?margin:\s*0/i);
  assert.match(theme, /\.mobile-cert summary/i);
  assert.doesNotMatch(theme, /#toolList\s*\{\s*min-height:/i);
  assert.match(theme, /\.setup\.setup-pending,[\s\S]*\.setup\.setup-hidden[\s\S]*display:\s*none/i);
  assert.doesNotMatch(theme, /\.client-list\s*\{\s*min-height:/i);
  assert.doesNotMatch(theme, /^\.history-list\s*\{\s*min-height:/im);
  assert.doesNotMatch(theme, /\.workspace > aside\.sidebar-boot/i);
  assert.doesNotMatch(theme, /@keyframes sidebar-first-paint/i);
  assert.match(theme, /\.connection\s*\{\s*min-width:\s*205px/i);
  assert.match(theme, /html\[data-theme="light"\] \.mobile-https-mark\s*\{[\s\S]*?background:\s*#0d1515;[\s\S]*?box-shadow:/i);
  assert.match(script, /network-card--scrollable\", analysis\.detections\.length > 7/);
  assert.doesNotMatch(theme, /\.network-card\.network-card--scrollable\s*\{[\s\S]*?height:\s*430px/i);
  assert.match(theme, /\.side-data-card > \.network-list,[\s\S]*?overflow-y:\s*auto/i);
  assert.match(theme, /\.side-data-card > \.history-list,[\s\S]*?max-height:\s*none/i);
  assert.match(html, /id="networkList" class="network-list auto-hide-scrollbar"/i);
  assert.match(html, /id="historyList" class="history-list auto-hide-scrollbar"/i);
  assert.match(html, /id="toolList" class="auto-hide-scrollbar"/i);
  assert.match(html, /id="clientList" class="client-list auto-hide-scrollbar"/i);
  assert.match(theme, /\.side-data-card\s*\{[\s\S]*?max-height:\s*430px/i);
  assert.match(theme, /html\[data-embedded="android"\] #toolCard\s*\{\s*display:\s*flex !important;/i);
  assert.match(theme, /@property --studio-scroll-thumb[\s\S]*?syntax: "<color>"/i);
  assert.match(theme, /\.auto-hide-scrollbar\s*\{[\s\S]*?transition: --studio-scroll-thumb 300ms ease-out/i);
  assert.match(script, /function enableAutoHideScrollbar\(element\)[\s\S]*?setTimeout\([\s\S]*?650\)/i);
  assert.match(script, /refreshStatus\(\);\s*refreshHistory\(\);/i);
  assert.doesNotMatch(script, /revealReadySidebar/i);
  assert.doesNotMatch(theme, /\.workspace-architecture/i);
  assert.match(theme, /\.mobile-https-banner\s*\{[\s\S]*?display:\s*grid/i);
  assert.match(theme, /@media \(min-width:\s*901px\)[\s\S]*?\.steps span\s*\{[\s\S]*?box-shadow:\s*inset 0 0 0 1px/i);
  assert.match(theme, /\.integrity-notice\s*\{[\s\S]*?margin-top:\s*14px/i);
  assert.match(theme, /transition:\s*border-color \.42s cubic-bezier/i);
  assert.match(theme, /\.choice-check::after\s*\{[\s\S]*?transform:\s*scale\(\.15\) rotate\(-18deg\)[\s\S]*?transition:\s*opacity \.3s ease, transform \.5s cubic-bezier/i);
  assert.match(theme, /input:checked\) \.choice-check::after\s*\{\s*opacity:\s*1;\s*transform:\s*scale\(1\) rotate\(0\)/i);
  assert.doesNotMatch(theme, /\.split-choice::before[\s\S]*?scaleX\(/i);
  assert.match(theme, /@keyframes result-pop/i);
  assert.match(theme, /@media\s*\(prefers-reduced-motion:\s*reduce\)/i);
  assert.match(theme, /html\[data-embedded="android"\] \.report-viewer[\s\S]*?android-status-inset/i);
  assert.match(theme, /orientation:\s*landscape[\s\S]*?html\[data-embedded="android"\] \.connection\s*\{[\s\S]*?align-self:\s*center;[\s\S]*?height:\s*38px/i);
  assert.match(script, /const hasIndependentPatch = \$\("#stripDebug"\)\.checked \|\| \$\("#normalizeDex"\)\.checked \|\| \$\("#optimizeApk"\)\.checked \|\| \$\("#deobfuscateResources"\)\.checked/i);
  assert.match(script, /Seçili işlemleri başlat/i);
  assert.match(script, /Play Store kaynak veya bütünlük denetimi riski algılandı/i);
  assert.match(html, /data-profile="deep"[^>]*>[\s\S]*?<b>Gelişmiş<\/b>/i);
  assert.match(theme, /\.special-thanks\s*\{[\s\S]*?grid-template-columns/i);
  assert.match(theme, /icons\/website\.svg/i);
  assert.match(theme, /icons\/telegram-plane\.svg/i);
  assert.match(theme, /icons\/github\.svg/i);
  assert.match(theme, /\.footer-links a\s*\{[\s\S]*?align-items:\s*center;[\s\S]*?flex-direction:\s*row;/i);
  assert.doesNotMatch(theme, /\.footer-links a\s*\{[^}]*flex-direction:\s*column/i);
  assert.ok(repoIcon.byteLength > 100_000);
  assert.match(websiteIcon, /<svg[\s\S]*<path/i);
  assert.match(telegramIcon, /<svg[\s\S]*<path/i);
  assert.match(githubIcon, /<svg[\s\S]*<path/i);
});
